# Generated by Django 5.2.6 on 2026-03-10 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategicPillar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("business_objective", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="HRStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("organization_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "HR Strategies",
            },
        ),
        migrations.CreateModel(
            name="StrategicInitiative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("objective", models.TextField()),
                ("scope", models.TextField(blank=True)),
                ("timeline_start", models.DateField(blank=True, null=True)),
                ("timeline_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiatives",
                        to="hr_strategy.strategicpillar",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyExecutionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "module_name",
                    models.CharField(
                        help_text="e.g. recruitment, performance, tna", max_length=100
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("linked", "Linked"),
                            ("active", "Active"),
                            ("broken", "Broken"),
                            ("inactive", "Inactive"),
                        ],
                        default="linked",
                        max_length=20,
                    ),
                ),
                ("execution_data", models.JSONField(default=dict)),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_links",
                        to="hr_strategy.strategicinitiative",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyExplainability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "entity_type",
                    models.CharField(help_text="pillar / initiative", max_length=50),
                ),
                ("entity_id", models.UUIDField()),
                ("explanation_text", models.TextField()),
                ("data_sources", models.JSONField(default=list)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="hr_strategy_entity__85e4d9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategyKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("kpi_name", models.CharField(max_length=200)),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("current_value", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "measurement_frequency",
                    models.CharField(default="monthly", max_length=50),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="hr_strategy.strategicinitiative",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyReadinessScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("readiness_score", models.FloatField(help_text="0-100")),
                (
                    "scoring_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="maturity, capability, culture, resources",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_scores",
                        to="hr_strategy.strategicinitiative",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyRiskAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("talent", "Talent"),
                            ("financial", "Financial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("impact_description", models.TextField()),
                ("mitigation", models.TextField(blank=True)),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="hr_strategy.strategicinitiative",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Strategy Risk Analyses",
            },
        ),
        migrations.CreateModel(
            name="StrategyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hr_strategy.hrstrategy",
                    ),
                ),
            ],
            options={
                "unique_together": {("strategy", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="StrategyRoadmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("phase_name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("milestones", models.JSONField(default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to="hr_strategy.strategyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StrategyConfidenceLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("aggregate_readiness", models.FloatField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confidence_levels",
                        to="hr_strategy.strategyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyBenchmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "benchmark_type",
                    models.CharField(
                        choices=[
                            ("industry", "Industry"),
                            ("size", "Company Size"),
                            ("region", "Region"),
                        ],
                        max_length=20,
                    ),
                ),
                ("variance_data", models.JSONField(default=dict)),
                ("dataset_version", models.CharField(blank=True, max_length=50)),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benchmarks",
                        to="hr_strategy.strategyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="strategicpillar",
            name="strategy_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillars",
                to="hr_strategy.strategyversion",
            ),
        ),
        migrations.AddField(
            model_name="hrstrategy",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr_strategy.strategyversion",
            ),
        ),
        migrations.CreateModel(
            name="InitiativeDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("dependency_type", models.CharField(default="blocks", max_length=50)),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="hr_strategy.strategicinitiative",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="hr_strategy.strategicinitiative",
                    ),
                ),
            ],
            options={
                "unique_together": {("initiative", "depends_on")},
            },
        ),
    ]
