# Generated by Django 5.2.6 on 2026-03-10 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="hiring / mobility / succession / promotion",
                        max_length=100,
                    ),
                ),
                ("rule_name", models.CharField(max_length=255)),
                ("rule_definition", models.JSONField(default=dict)),
                ("priority", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Business Rule",
                "ordering": ["category", "priority"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("referral", "Referral"),
                            ("direct", "Direct"),
                            ("internal", "Internal"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                ("source_detail", models.JSONField(blank=True, default=dict)),
                ("cv_file_path", models.CharField(blank=True, max_length=500)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                ("competencies_extracted", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Candidate",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JDCompetencyMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("jd_id", models.UUIDField(db_index=True)),
                ("competency_id", models.CharField(max_length=255)),
                ("competency_name", models.CharField(max_length=255)),
                ("proficiency_level", models.CharField(max_length=50)),
                ("is_critical", models.BooleanField(default=False)),
                (
                    "weight_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "JD Competency Mapping",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobAdPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("career_portal", "Career Portal"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("platform_job_id", models.CharField(blank=True, max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "budget_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Ad Publication",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobAdvertisement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("generated_content", models.TextField(blank=True)),
                ("template_id", models.UUIDField(blank=True, null=True)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("bold", "Bold"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("detailed", "Detailed"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("seo_keywords", models.JSONField(blank=True, default=list)),
                ("company_branding", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Job Advertisement",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrityBaseline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("role_level", models.CharField(max_length=100)),
                ("question_difficulty", models.CharField(max_length=50)),
                (
                    "avg_attention_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("avg_look_away_duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "anomaly_threshold_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("sample_size", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Integrity Baseline",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("role_level", "question_difficulty")},
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ai_avatar", "AI Avatar"),
                            ("traditional", "Traditional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interview_stage",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("technical", "Technical"),
                            ("hr", "HR"),
                            ("manager", "Manager"),
                            ("panel", "Panel"),
                        ],
                        default="screening",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("integrity_monitoring_enabled", models.BooleanField(default=False)),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_timestamp", models.DateTimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("meeting_link", models.URLField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("video_file_path", models.CharField(blank=True, max_length=500)),
                ("transcript_file_path", models.CharField(blank=True, max_length=500)),
                ("analysis_data", models.JSONField(blank=True, default=dict)),
                ("integrity_analysis_data", models.JSONField(blank=True, default=dict)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruiter.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntegrityDataAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("export", "Export"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_access_logs",
                        to="recruiter.interview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrity Data Access Log",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("integrity_monitoring", "Integrity Monitoring"),
                            ("data_processing", "Data Processing"),
                            ("communication", "Communication"),
                        ],
                        max_length=30,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_text_shown", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="recruiter.candidate",
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="recruiter.interview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Record",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("external_calendar_id", models.CharField(blank=True, max_length=255)),
                ("calendar_provider", models.CharField(blank=True, max_length=50)),
                ("event_link", models.URLField(blank=True, max_length=500)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="recruiter.interview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("interview_types", models.JSONField(blank=True, default=list)),
                ("competency_expertise", models.JSONField(blank=True, default=list)),
                ("max_interviews_per_week", models.PositiveIntegerField(default=5)),
                (
                    "avg_rating_given",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_interviews_conducted", models.PositiveIntegerField(default=0)),
                (
                    "feedback_quality_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("last_calibration_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interviewer Profile",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewerAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(help_text="0=Monday, 6=Sunday"),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("buffer_minutes_between", models.PositiveIntegerField(default=15)),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="recruiter.interviewerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interviewer Availability",
                "verbose_name_plural": "Interviewer Availabilities",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(help_text="1-5 rating"),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("strong_hire", "Strong Hire"),
                            ("hire", "Hire"),
                            ("maybe", "Maybe"),
                            ("no_hire", "No Hire"),
                            ("strong_no", "Strong No"),
                        ],
                        max_length=20,
                    ),
                ),
                ("competency_ratings", models.JSONField(blank=True, default=dict)),
                ("strengths", models.TextField(blank=True)),
                ("concerns", models.TextField(blank=True)),
                ("red_flags", models.TextField(blank=True)),
                (
                    "cultural_fit_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "communication_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "technical_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("open_feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="recruiter.interview",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Feedback",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedbackCalibration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("calibration_session_date", models.DateField()),
                ("original_scores", models.JSONField(default=dict)),
                ("calibrated_scores", models.JSONField(default=dict)),
                (
                    "consensus_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("discrepancies_noted", models.TextField(blank=True)),
                ("calibration_notes", models.TextField(blank=True)),
                ("calibrated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calibrated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibrations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibrations",
                        to="recruiter.interview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Calibration",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewIntegrityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "overall_integrity_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("anomaly_count", models.PositiveIntegerField(default=0)),
                (
                    "total_look_away_time_seconds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "attention_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("behavioral_patterns", models.JSONField(blank=True, default=dict)),
                ("context_adjustments", models.JSONField(blank=True, default=dict)),
                ("ai_reasoning", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_report",
                        to="recruiter.interview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrity Report",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewInterviewer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("panel", "Panel"),
                            ("observer", "Observer"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("calendar_event_id", models.CharField(blank=True, max_length=255)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("feedback_submitted", models.BooleanField(default=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewers",
                        to="recruiter.interview",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Interviewer",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("question_text", models.TextField()),
                ("competency_mapped", models.CharField(blank=True, max_length=255)),
                ("jd_competency_id", models.UUIDField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "expected_response_time_seconds",
                    models.PositiveIntegerField(default=120),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("situational", "Situational"),
                        ],
                        default="behavioral",
                        max_length=20,
                    ),
                ),
                ("order_sequence", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="recruiter.interview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Question",
                "ordering": ["order_sequence"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewIntegritySignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("timestamp", models.DateTimeField()),
                ("eye_gaze_x", models.FloatField(default=0)),
                ("eye_gaze_y", models.FloatField(default=0)),
                ("on_screen", models.BooleanField(default=True)),
                ("look_away_duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "attention_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("head_pose_angles", models.JSONField(blank=True, default=dict)),
                ("anomaly_detected", models.BooleanField(default=False)),
                ("anomaly_type", models.CharField(blank=True, max_length=100)),
                (
                    "question_difficulty_context",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "baseline_deviation_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_signals",
                        to="recruiter.interview",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruiter.interviewquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrity Signal",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("response_text", models.TextField(blank=True)),
                ("video_timestamp_start", models.FloatField(blank=True, null=True)),
                ("video_timestamp_end", models.FloatField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "jd_competency_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("ai_feedback", models.JSONField(blank=True, default=dict)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="recruiter.interview",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="recruiter.interviewquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Response",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobAdAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("date", models.DateField(db_index=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("applications", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cost_per_application",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "source_quality_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="recruiter.jobadpublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Ad Analytics",
                "verbose_name_plural": "Job Ad Analytics",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="jobadpublication",
            name="job_ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="recruiter.jobadvertisement",
            ),
        ),
        migrations.CreateModel(
            name="PromotionCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("cycle_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("total_eligible_employees", models.PositiveIntegerField(default=0)),
                ("total_promoted", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Cycle",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("current_jd_id", models.UUIDField(blank=True, null=True)),
                ("target_jd_id", models.UUIDField(blank=True, null=True)),
                ("current_role", models.CharField(max_length=255)),
                ("proposed_role", models.CharField(max_length=255)),
                (
                    "promotion_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("jd_competency_delta", models.JSONField(blank=True, default=dict)),
                (
                    "eligibility_status",
                    models.CharField(default="eligible", max_length=30),
                ),
                ("failed_rules", models.JSONField(blank=True, default=list)),
                ("justification", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotion_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="recruiter.promotioncycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RuleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.UUIDField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_exception_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rule_exception_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="recruiter.businessrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Exception",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuccessionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("critical_role_id", models.UUIDField(db_index=True)),
                ("target_jd_id", models.UUIDField()),
                (
                    "readiness_level",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("6_12mo", "6-12 months"),
                            ("12_plus", "12+ months"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "jd_competency_gap_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("competency_data", models.JSONField(blank=True, default=dict)),
                ("development_plan", models.JSONField(blank=True, default=dict)),
                ("business_rules_validated", models.BooleanField(default=False)),
                ("validation_notes", models.TextField(blank=True)),
                (
                    "successor_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="succession_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Succession Plan",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "jd_id",
                    models.UUIDField(help_text="FK to JD Engine job description"),
                ),
                ("jd_version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("role_level", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(db_index=True, max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "job_ad_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_internal", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy",
                "verbose_name_plural": "Vacancies",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="jobadvertisement",
            name="vacancy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_ad",
                to="recruiter.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="interviewquestion",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_questions",
                to="recruiter.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="recruiter.vacancy",
            ),
        ),
        migrations.CreateModel(
            name="InternalMobility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("target_jd_id", models.UUIDField()),
                ("current_jd_id", models.UUIDField(blank=True, null=True)),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("self_nomination", "Self Nomination"),
                            ("manager_recommendation", "Manager Recommendation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "role_fit_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("jd_competency_match", models.JSONField(blank=True, default=dict)),
                ("skill_gaps", models.JSONField(blank=True, default=list)),
                ("gap_closure_timeline_months", models.PositiveIntegerField(default=0)),
                (
                    "eligibility_status",
                    models.CharField(default="eligible", max_length=30),
                ),
                ("failed_rules", models.JSONField(blank=True, default=list)),
                ("manager_endorsement", models.BooleanField(default=False)),
                ("endorsed_at", models.DateTimeField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endorsed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mobility_endorsements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_applications",
                        to="recruiter.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Mobility",
                "verbose_name_plural": "Internal Mobility Records",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HiringDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("hire", "Hire"),
                            ("reject", "Reject"),
                            ("hold", "Hold"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cv_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "interview_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "traditional_interview_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "integrity_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "combined_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "jd_match_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("business_rules_passed", models.BooleanField(default=True)),
                ("failed_rules", models.JSONField(blank=True, default=list)),
                ("ai_reasoning", models.JSONField(blank=True, default=dict)),
                (
                    "hr_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Approved"),
                            ("overridden", "Overridden"),
                        ],
                        max_length=20,
                    ),
                ),
                ("override_reason", models.TextField(blank=True)),
                (
                    "cost_per_hire",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("time_to_hire_days", models.PositiveIntegerField(default=0)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="recruiter.candidate",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="recruiter.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hiring Decision",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateCommunicationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("call", "Call"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="recruiter.candidate",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="recruiter.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Log",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateVacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "cv_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "interview_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "traditional_interview_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "integrity_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "combined_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "jd_match_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("ai_reasoning", models.JSONField(blank=True, default=dict)),
                ("jd_competency_gaps", models.JSONField(blank=True, default=list)),
                ("rank_position", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("screened", "Screened"),
                            ("interviewed", "Interviewed"),
                            ("offered", "Offered"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruiter.candidate",
                    ),
                ),
                (
                    "application_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recruiter.jobadpublication",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruiter.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Application",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("candidate", "vacancy")},
            },
        ),
    ]
