# Generated by Django 5.2.6 on 2026-03-10 23:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAnalysisInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("role_title", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                (
                    "tasks",
                    models.JSONField(
                        default=list, help_text="List of main tasks/responsibilities"
                    ),
                ),
                (
                    "tools",
                    models.JSONField(default=list, help_text="Tools and systems used"),
                ),
                ("reporting_line", models.CharField(blank=True, max_length=255)),
                ("working_conditions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Analysis Input",
                "verbose_name_plural": "Job Analysis Inputs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_jds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_jds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_descriptions",
                        to="job_description.jobanalysisinput",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Description",
                "verbose_name_plural": "Job Descriptions",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobDescriptionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version_number", models.PositiveIntegerField()),
                (
                    "structured_model",
                    models.JSONField(
                        default=dict,
                        help_text="Full structured JD: purpose, responsibilities, competencies, KPIs",
                    ),
                ),
                ("benchmark_summary", models.JSONField(blank=True, default=dict)),
                ("validation_results", models.JSONField(blank=True, default=dict)),
                (
                    "jd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="job_description.jobdescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "JD Version",
                "verbose_name_plural": "JD Versions",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("jd", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="job_description.jobdescriptionversion",
            ),
        ),
        migrations.CreateModel(
            name="JDConsumerReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "consumer_service",
                    models.CharField(
                        help_text="Recruiter / Performance / TNA / Mobility",
                        max_length=100,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        help_text="Vacancy / KPI / Promotion", max_length=50
                    ),
                ),
                ("referenced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jd_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_references",
                        to="job_description.jobdescriptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "JD Consumer Reference",
                "verbose_name_plural": "JD Consumer References",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JDCompetency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("competency_name", models.CharField(max_length=255)),
                (
                    "proficiency_level",
                    models.CharField(
                        help_text="Junior / Mid / Senior / Expert", max_length=50
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weight percentage",
                        max_digits=5,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "jd_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="job_description.jobdescriptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "JD Competency",
                "verbose_name_plural": "JD Competencies",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JDBenchmarkResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "benchmark_source",
                    models.CharField(
                        help_text="O*NET / ESCO / Industry DB", max_length=100
                    ),
                ),
                ("deviations", models.JSONField(default=dict)),
                ("risk_flags", models.TextField(blank=True)),
                (
                    "jd_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benchmarks",
                        to="job_description.jobdescriptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "JD Benchmark Result",
                "verbose_name_plural": "JD Benchmark Results",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JDApprovalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jd_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="job_description.jobdescriptionversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "JD Approval Log",
                "verbose_name_plural": "JD Approval Logs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
